"""initial schema

Revision ID: 90b4e125346f
Revises: 
Create Date: 2026-07-27 17:25:12.169487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b4e125346f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('pesquisas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('termo_busca', sa.String(), nullable=False),
    sa.Column('quantidade_desejada', sa.String(), nullable=True),
    sa.Column('limite_processos', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('resultado_json', sa.Text(), nullable=True),
    sa.Column('pasta_downloads', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesquisas_id'), 'pesquisas', ['id'], unique=False)
    op.create_table('uso_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('tokens_total', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uso_tokens_id'), 'uso_tokens', ['id'], unique=False)
    op.create_table('analises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pesquisa_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('resultado_json', sa.Text(), nullable=True),
    sa.Column('modelo_gemini', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pesquisa_id'], ['pesquisas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analises_id'), 'analises', ['id'], unique=False)
    op.create_table('geracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pesquisa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('resultado_json', sa.Text(), nullable=True),
    sa.Column('arquivo_gerado', sa.String(), nullable=True),
    sa.Column('modelo_gemini', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pesquisa_id'], ['pesquisas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geracoes_id'), 'geracoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geracoes_id'), table_name='geracoes')
    op.drop_table('geracoes')
    op.drop_index(op.f('ix_analises_id'), table_name='analises')
    op.drop_table('analises')
    op.drop_index(op.f('ix_uso_tokens_id'), table_name='uso_tokens')
    op.drop_table('uso_tokens')
    op.drop_index(op.f('ix_pesquisas_id'), table_name='pesquisas')
    op.drop_table('pesquisas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
