"""add_contratacao_tables

Revision ID: 99d7acabe483
Revises: 90b4e125346f
Create Date: 2026-08-04 16:27:18.234008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d7acabe483'
down_revision: Union[str, Sequence[str], None] = '90b4e125346f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('orgao_unidade', sa.String(length=500), nullable=False),
    sa.Column('numero_processo', sa.String(length=200), nullable=True),
    sa.Column('equipe_responsavel', sa.Text(), nullable=True),
    sa.Column('tipo_contratacao', sa.String(length=100), nullable=True),
    sa.Column('contexto_inicial', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='cadastro', nullable=False),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratacoes_id'), 'contratacoes', ['id'], unique=False)
    op.create_table('bases_conhecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contratacao_id', sa.Integer(), nullable=False),
    sa.Column('dados_json', sa.Text(), nullable=False),
    sa.Column('progresso_pct', sa.Integer(), server_default='0', nullable=True),
    sa.Column('nivel_maturidade', sa.String(length=20), server_default='Insuficiente', nullable=True),
    sa.Column('modelo_gemini', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contratacao_id')
    )
    op.create_index(op.f('ix_bases_conhecimento_id'), 'bases_conhecimento', ['id'], unique=False)
    op.create_table('historico_contratacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contratacao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=500), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_contratacao_id'), 'historico_contratacao', ['id'], unique=False)
    op.create_table('perguntas_contratacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contratacao_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('alternativas_json', sa.Text(), nullable=False),
    sa.Column('resposta_escolhida', sa.String(length=1), nullable=True),
    sa.Column('respondida_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perguntas_contratacao_id'), 'perguntas_contratacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perguntas_contratacao_id'), table_name='perguntas_contratacao')
    op.drop_table('perguntas_contratacao')
    op.drop_index(op.f('ix_historico_contratacao_id'), table_name='historico_contratacao')
    op.drop_table('historico_contratacao')
    op.drop_index(op.f('ix_bases_conhecimento_id'), table_name='bases_conhecimento')
    op.drop_table('bases_conhecimento')
    op.drop_index(op.f('ix_contratacoes_id'), table_name='contratacoes')
    op.drop_table('contratacoes')
    # ### end Alembic commands ###
